---

name: Release
on:
  - push

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
        include:
            - target: armv7-unknown-linux-gnueabihf
              os: ubuntu-latest
              cross: true
            - target: x86_64-unknown-linux-gnu
              os: ubuntu-latest
              cross: false
    name: "Build for ${{ matrix.target }}"
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          use-cross: "${{ matrix.cross }}"
          command: build
          args: --target ${{ matrix.target }} --release

