---

name: Release
on:
  - push

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-pc-windows-msvc
        include:
            - target: armv7-unknown-linux-gnueabihf
              os: ubuntu-latest
              cross: true
              build-controller: true
              build-agent: false
            - target: x86_64-unknown-linux-gnu
              os: ubuntu-latest
              cross: false
              build-controller: true
              build-agent: true
            - target: x86_64-pc-windows-msvc
              os: windows-latest
              cross: false
              build-controller: false
              build-agent: true
    name: "Build for ${{ matrix.target }}"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt
          target: "${{ matrix.target }}"

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build samwise-controller
        uses: actions-rs/cargo@v1
        with:
          use-cross: "${{ matrix.cross }}"
          command: build
          args: --target ${{ matrix.target }} --release -p samwise-controller
        if: matrix.build-controller
      
      - name: Build samwise-agent
        uses: actions-rs/cargo@v1
        with:
          use-cross: "${{ matrix.cross }}"
          command: build
          args: --target ${{ matrix.target }} --release -p samwise-agent
        if: matrix.build-agent

